
language: php

php:
    - 5.6
    - 7.0
    - hhvm

sudo: false

services:
    - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

env:
  - SYMFONY_VERSION="3.2.*" DB=mysql

before-install:
  - composer self-update

install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit

notifications:
  email: false
