parameters:

services:
    app.host-repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CBList\ModelBundle\Entity\Host

    app.category-repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CBList\ModelBundle\Entity\Category

    app.report-repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - CBList\ModelBundle\Entity\Report

    app.host-service:
        class:      CBList\ModelBundle\Service\HostService
        arguments:  ['@doctrine.orm.default_entity_manager', '@app.host-repository']

    app.category-service:
        class:      CBList\ModelBundle\Service\CategoryService
        arguments:  ['@doctrine.orm.default_entity_manager', '@app.category-repository']
